/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eldenringproj;

import bo.Enemy;
import dao.EnemyHandler;
import dao.MobHandler;
import dao.BossHandler;
import dao.InventoryHandler;
import eldenringproj.EditEnemy;
import java.util.Iterator;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import utils.SQLUtil;
/**
 *
 * @author kilch
 */
public class BossOrMob extends javax.swing.JFrame {

    /**
     * Creates new form BossOrMob
     */
    public BossOrMob() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMobID = new javax.swing.JTextField();
        txtMobName = new javax.swing.JTextField();
        txtMobHealth = new javax.swing.JTextField();
        txtMobDMG = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        CreateBossBttn = new javax.swing.JButton();
        EnemyMenuBttn = new javax.swing.JButton();
        txtBossID = new javax.swing.JTextField();
        txtBossName = new javax.swing.JTextField();
        txtBossHealth = new javax.swing.JTextField();
        txtBossDMG = new javax.swing.JTextField();
        txtAbilitySet = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(544, 250, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(213, 174, 88));
        jLabel1.setText("Mob");

        jLabel2.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(213, 174, 88));
        jLabel2.setText("Boss");

        jLabel3.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(213, 174, 88));
        jLabel3.setText("Enemy ID: ");

        jLabel4.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(213, 174, 88));
        jLabel4.setText("Mob Name: ");

        jLabel5.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(213, 174, 88));
        jLabel5.setText("Mob Health: ");

        jLabel6.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(213, 174, 88));
        jLabel6.setText("Mob Damage: ");

        jLabel7.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(213, 174, 88));
        jLabel7.setText("Enemy ID: ");

        jLabel8.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(213, 174, 88));
        jLabel8.setText("Boss Name: ");

        jLabel9.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(213, 174, 88));
        jLabel9.setText("Boss Health");

        jLabel10.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(213, 174, 88));
        jLabel10.setText("Boss Damage: ");

        jLabel11.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(213, 174, 88));
        jLabel11.setText("Ability Set: ");

        txtMobID.setBackground(new java.awt.Color(213, 174, 88));
        txtMobID.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        txtMobName.setBackground(new java.awt.Color(213, 174, 88));
        txtMobName.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        txtMobHealth.setBackground(new java.awt.Color(213, 174, 88));
        txtMobHealth.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        txtMobDMG.setBackground(new java.awt.Color(213, 174, 88));
        txtMobDMG.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        jButton1.setBackground(new java.awt.Color(213, 174, 88));
        jButton1.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        jButton1.setText("Create Mob");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CreateBossBttn.setBackground(new java.awt.Color(213, 174, 88));
        CreateBossBttn.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        CreateBossBttn.setText("Create Boss");
        CreateBossBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBossBttnActionPerformed(evt);
            }
        });

        EnemyMenuBttn.setBackground(new java.awt.Color(213, 174, 88));
        EnemyMenuBttn.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        EnemyMenuBttn.setText("Back to Enemy");
        EnemyMenuBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnemyMenuBttnActionPerformed(evt);
            }
        });

        txtBossID.setBackground(new java.awt.Color(213, 174, 88));
        txtBossID.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        txtBossName.setBackground(new java.awt.Color(213, 174, 88));
        txtBossName.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        txtBossHealth.setBackground(new java.awt.Color(213, 174, 88));
        txtBossHealth.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        txtBossDMG.setBackground(new java.awt.Color(213, 174, 88));
        txtBossDMG.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        txtAbilitySet.setBackground(new java.awt.Color(213, 174, 88));
        txtAbilitySet.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37)
                        .addComponent(EnemyMenuBttn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMobHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBossHealth))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMobDMG))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMobID, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMobName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAbilitySet))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBossID, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBossName))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBossDMG)))))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CreateBossBttn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(EnemyMenuBttn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtMobID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBossID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(txtMobName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBossName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMobHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtBossHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMobDMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtBossDMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtAbilitySet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(CreateBossBttn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// Create instances of the necessary classes for handling enemies and mobs
EnemyHandler EnemyHand = new EnemyHandler();
EditEnemy EE = new EditEnemy();
MobHandler MobHand = new MobHandler();

// Get values from text fields for mob ID, name, health, and damage
String MobID = txtMobID.getText();
String MobName = txtMobName.getText();
String MobHealth = txtMobHealth.getText();
String MobDMG = txtMobDMG.getText();

try {
    // Convert string inputs to integers for mob ID, health, and damage
    int mobID = Integer.parseInt(MobID);
    int mobHealth = Integer.parseInt(MobHealth);
    int mobDMG = Integer.parseInt(MobDMG);

    // Call methods to add new enemy and mob instances
    int result2 = EnemyHand.addEnemy(mobID, MobName, mobHealth, mobDMG);
    int result = MobHand.addMob(mobID);

    // Check if both enemy and mob were successfully added
    if (result > 0 && result2 > 0) {
        // If successful, hide current window, open edit window, refresh table, and show success message
        this.setVisible(false);
        new EditEnemy().setVisible(true);
        EE.refreshEnemyTable();
        JOptionPane.showMessageDialog(this, "Updated");
    } else {
        // If adding failed, display a failure message
    }
} catch (NumberFormatException e) {
    // Handle the exception for invalid integer input
    e.printStackTrace();
}


    }//GEN-LAST:event_jButton1ActionPerformed

    private void CreateBossBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBossBttnActionPerformed
// Create instances of the necessary classes for handling enemies, bosses, and editing
EnemyHandler EnemyHand = new EnemyHandler();
EditEnemy EE = new EditEnemy();
BossHandler BossHand = new BossHandler();

// Get values from text fields for boss ID, name, health, damage, and ability set
String BossID = txtBossID.getText();
String BossName = txtBossName.getText();
String BossHealth = txtBossHealth.getText();
String BossDMG = txtBossDMG.getText();
String BossAbilitySet = txtAbilitySet.getText();

try {
    // Convert string inputs to integers for boss ID, health, and damage
    int bossID = Integer.parseInt(BossID);
    int bossHealth = Integer.parseInt(BossHealth);
    int bossDMG = Integer.parseInt(BossDMG);

    // Call methods to add new enemy and boss instances
    int result2 = EnemyHand.addEnemy(bossID, BossName, bossHealth, bossDMG);
    int result = BossHand.addBoss(bossID, BossAbilitySet);

    // Check if both enemy and boss were successfully added
    if (result > 0 && result2 > 0) {
        // If successful, hide current window, open edit window, refresh table, and show success message
        this.setVisible(false);
        new EditEnemy().setVisible(true);
        EE.refreshEnemyTable();
        JOptionPane.showMessageDialog(this, "Updated");
    } else {
        // If adding failed, display a failure message
        JOptionPane.showMessageDialog(this, "Failed to update");
    }
} catch (NumberFormatException e) {
    // Handle the exception for invalid integer input
    e.printStackTrace();
}
    }//GEN-LAST:event_CreateBossBttnActionPerformed

    private void EnemyMenuBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnemyMenuBttnActionPerformed
        this.setVisible(false);
        new EditEnemy().setVisible(true);
    }//GEN-LAST:event_EnemyMenuBttnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateBossBttn;
    private javax.swing.JButton EnemyMenuBttn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAbilitySet;
    private javax.swing.JTextField txtBossDMG;
    private javax.swing.JTextField txtBossHealth;
    private javax.swing.JTextField txtBossID;
    private javax.swing.JTextField txtBossName;
    private javax.swing.JTextField txtMobDMG;
    private javax.swing.JTextField txtMobHealth;
    private javax.swing.JTextField txtMobID;
    private javax.swing.JTextField txtMobName;
    // End of variables declaration//GEN-END:variables
}
