/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eldenringproj;

import bo.Enemy;
import dao.EnemyHandler;
import java.util.Iterator;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import utils.SQLUtil;
/**
 *
 * @author kilch
 */
public class EditEnemy extends javax.swing.JFrame {

List<Enemy> EnemyL;
    
    private void populateData(String keyword) {
        String[] colNames = new String[]{"Enemy ID", "Enemy Name","Enemy Health", "Enemy Damage"};
        DefaultTableModel tm = new DefaultTableModel(colNames, 0) {
            @Override
            public boolean isCellEditable(int i, int i1) {
                return false;
            }
        };
        EnemyL = new EnemyHandler().getEnemy(keyword);
        EnemyL.forEach((s) -> {
            tm.addRow(s.getRow());
        });
        tblEnemy.setModel(tm);
    }
    public EditEnemy() {
        initComponents();
        populateData("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txteID = new javax.swing.JTextField();
        txteName = new javax.swing.JTextField();
        txteHealth = new javax.swing.JTextField();
        txteDamage = new javax.swing.JTextField();
        eAddBttn = new javax.swing.JButton();
        eUpdateBttn = new javax.swing.JButton();
        eDeleteBttn = new javax.swing.JButton();
        eMenuBttn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnemy = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Gabriola", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(213, 174, 88));
        jLabel1.setText("Edit Enemy");

        jLabel2.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(213, 174, 88));
        jLabel2.setText("Enemy ID:");

        jLabel3.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(213, 174, 88));
        jLabel3.setText("Enemy Name:");

        jLabel4.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(213, 174, 88));
        jLabel4.setText("Enemy Health:");

        jLabel5.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(213, 174, 88));
        jLabel5.setText("Enemy Damage:");

        txteID.setBackground(new java.awt.Color(213, 174, 88));
        txteID.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        txteName.setBackground(new java.awt.Color(213, 174, 88));
        txteName.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        txteHealth.setBackground(new java.awt.Color(213, 174, 88));
        txteHealth.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        txteDamage.setBackground(new java.awt.Color(213, 174, 88));
        txteDamage.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        eAddBttn.setBackground(new java.awt.Color(213, 174, 88));
        eAddBttn.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        eAddBttn.setText("Create Mob/Boss");
        eAddBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eAddBttnActionPerformed(evt);
            }
        });

        eUpdateBttn.setBackground(new java.awt.Color(213, 174, 88));
        eUpdateBttn.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        eUpdateBttn.setText("Update Data");
        eUpdateBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eUpdateBttnActionPerformed(evt);
            }
        });

        eDeleteBttn.setBackground(new java.awt.Color(213, 174, 88));
        eDeleteBttn.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        eDeleteBttn.setText("Delete Data");
        eDeleteBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eDeleteBttnActionPerformed(evt);
            }
        });

        eMenuBttn.setBackground(new java.awt.Color(213, 174, 88));
        eMenuBttn.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        eMenuBttn.setText("Menu");
        eMenuBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMenuBttnActionPerformed(evt);
            }
        });

        tblEnemy.setBackground(new java.awt.Color(0, 0, 0));
        tblEnemy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblEnemy.setForeground(new java.awt.Color(213, 174, 88));
        tblEnemy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEnemy.setRowHeight(30);
        tblEnemy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEnemyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEnemy);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txteDamage))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txteID, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txteName, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txteHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eUpdateBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eDeleteBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eAddBttn, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(eMenuBttn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txteName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txteHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txteDamage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(eAddBttn)
                        .addGap(18, 18, 18)
                        .addComponent(eUpdateBttn)
                        .addGap(18, 18, 18)
                        .addComponent(eDeleteBttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(eMenuBttn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblEnemyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEnemyMouseClicked
        int selectedRow = tblEnemy.getSelectedRow();
        if (selectedRow != -1) {
                    // Get values from the selected row
                    Object eIDValue = tblEnemy.getValueAt(selectedRow, 0);
                    Object eNameValue = tblEnemy.getValueAt(selectedRow, 1);
                    Object eHealthValue = tblEnemy.getValueAt(selectedRow, 2);
                    Object eDamageValue = tblEnemy.getValueAt(selectedRow,3);

                    // Set text fields with the retrieved values
                    txteID.setText(String.valueOf(eIDValue));
                    txteName.setText(String.valueOf(eNameValue));
                    txteHealth.setText(String.valueOf(eHealthValue));
                    txteDamage.setText(String.valueOf(eDamageValue));
                    
                }
    }//GEN-LAST:event_tblEnemyMouseClicked

    private void eUpdateBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eUpdateBttnActionPerformed
// Create an instance of the EnemyHandler class
EnemyHandler EnemyHand = new EnemyHandler();

// Get values from text fields for enemy ID, name, health, and damage
String enemyID = txteID.getText();
String enemyName = txteName.getText();
String enemyHealth = txteHealth.getText();
String enemyDamage = txteDamage.getText();

try {
    // Convert enemy ID, health, and damage to integers
    int intEnemyID = Integer.parseInt(enemyID);
    int intEnemyHealth = Integer.parseInt(enemyHealth);
    int intEnemyDamage = Integer.parseInt(enemyDamage);

    // Call the updateEnemy method to update enemy information
    int result = EnemyHand.updateEnemy(intEnemyID, intEnemyID, enemyName, intEnemyHealth, intEnemyDamage);

    // Check if the enemy was updated successfully
    if (result > 0) {
        // If successful, refresh the enemy table and show a success message
        refreshEnemyTable();
        JOptionPane.showMessageDialog(this, "Updated");
    } else {
        // If update failed, show a failure message
        JOptionPane.showMessageDialog(this, "Update Failed!");
    }
} catch (NumberFormatException e) {
    // Handle the exception for invalid integer input
    e.printStackTrace();
}

    }//GEN-LAST:event_eUpdateBttnActionPerformed

    private void eDeleteBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eDeleteBttnActionPerformed
        EnemyHandler EnemyHand = new EnemyHandler();
        
        String EnemyID = txteID.getText();
        
        int enemyID = Integer.parseInt(EnemyID);
        int result = EnemyHand.deleteEnemy(enemyID);
                
        if (result>0) {
            JOptionPane.showMessageDialog(this, "Armor deleted successfully.");
            refreshEnemyTable();}
        else{
            JOptionPane.showMessageDialog(this, "Armor deletion failed.");     
                    }
    }//GEN-LAST:event_eDeleteBttnActionPerformed

    private void eMenuBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMenuBttnActionPerformed
        this.setVisible(false);
        new EldenRingProj().setVisible(true);
    }//GEN-LAST:event_eMenuBttnActionPerformed

    private void eAddBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eAddBttnActionPerformed
        this.setVisible(false);
        new BossOrMob().setVisible(true);
    }//GEN-LAST:event_eAddBttnActionPerformed
    public void refreshEnemyTable(){
        populateData("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eAddBttn;
    private javax.swing.JButton eDeleteBttn;
    private javax.swing.JButton eMenuBttn;
    private javax.swing.JButton eUpdateBttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEnemy;
    private javax.swing.JTextField txteDamage;
    private javax.swing.JTextField txteHealth;
    private javax.swing.JTextField txteID;
    private javax.swing.JTextField txteName;
    // End of variables declaration//GEN-END:variables
}
