/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eldenringproj;

import bo.Class;
import dao.ClassHandler;
import java.util.Iterator;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import utils.SQLUtil;
/**
 *
 * @author kilch
 */
public class EditClass extends javax.swing.JFrame {

    
    List<Class> ClassL;
    
    private void populateData(String keyword) {
        String[] colNames = new String[]{"Class ID", "Class Name","Ability Type"};
        DefaultTableModel tm = new DefaultTableModel(colNames, 0) {
            @Override
            public boolean isCellEditable(int i, int i1) {
                return false;
            }
        };
        ClassL = new ClassHandler().getClass(keyword);
        ClassL.forEach((s) -> {
            tm.addRow(s.getRow());
        });
        tblClass.setModel(tm);
    }
    /**
     * Creates new form EditClass
     */
    public EditClass() {
        initComponents();
        populateData("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtClassID = new javax.swing.JTextField();
        txtClassName = new javax.swing.JTextField();
        txtAbilityType = new javax.swing.JTextField();
        cAddBttn = new javax.swing.JButton();
        cUpdateBttn = new javax.swing.JButton();
        cDeleteBttn = new javax.swing.JButton();
        cMenuBttn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClass = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Gabriola", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(213, 174, 88));
        jLabel1.setText("Edit Class");

        jLabel2.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(213, 174, 88));
        jLabel2.setText("Class ID: ");

        jLabel3.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(213, 174, 88));
        jLabel3.setText("Class Name: ");

        jLabel4.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(213, 174, 88));
        jLabel4.setText("Ability Type: ");

        txtClassID.setBackground(new java.awt.Color(213, 174, 88));
        txtClassID.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        txtClassName.setBackground(new java.awt.Color(213, 174, 88));
        txtClassName.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        txtAbilityType.setBackground(new java.awt.Color(213, 174, 88));
        txtAbilityType.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        cAddBttn.setBackground(new java.awt.Color(213, 174, 88));
        cAddBttn.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        cAddBttn.setText("Add New Class");
        cAddBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cAddBttnActionPerformed(evt);
            }
        });

        cUpdateBttn.setBackground(new java.awt.Color(213, 174, 88));
        cUpdateBttn.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        cUpdateBttn.setText("Update Data");
        cUpdateBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUpdateBttnActionPerformed(evt);
            }
        });

        cDeleteBttn.setBackground(new java.awt.Color(213, 174, 88));
        cDeleteBttn.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        cDeleteBttn.setText("Delete Data");
        cDeleteBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDeleteBttnActionPerformed(evt);
            }
        });

        cMenuBttn.setBackground(new java.awt.Color(213, 174, 88));
        cMenuBttn.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        cMenuBttn.setText("Menu");
        cMenuBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMenuBttnActionPerformed(evt);
            }
        });

        tblClass.setBackground(new java.awt.Color(0, 0, 0));
        tblClass.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        tblClass.setForeground(new java.awt.Color(213, 174, 88));
        tblClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClass.setRowHeight(30);
        tblClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClassMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClass);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClassID, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClassName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAbilityType)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cMenuBttn))
                    .addComponent(cUpdateBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cDeleteBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cAddBttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtClassID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAbilityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(cAddBttn)
                        .addGap(18, 18, 18)
                        .addComponent(cUpdateBttn)
                        .addGap(18, 18, 18)
                        .addComponent(cDeleteBttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cMenuBttn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClassMouseClicked
        int selectedRow = tblClass.getSelectedRow();
        if (selectedRow != -1) {
                    // Get values from the selected row
                    Object classIDValue = tblClass.getValueAt(selectedRow, 0);
                    Object classNameValue = tblClass.getValueAt(selectedRow, 1);
                    Object abilityType = tblClass.getValueAt(selectedRow, 2);

                    // Set text fields with the retrieved values
                    txtClassID.setText(String.valueOf(classIDValue));
                    txtClassName.setText(String.valueOf(classNameValue));
                    txtAbilityType.setText(String.valueOf(abilityType));
                    
                } 
    }//GEN-LAST:event_tblClassMouseClicked

    private void cUpdateBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUpdateBttnActionPerformed
// Create an instance of the ClassHandler class
ClassHandler ClassHand = new ClassHandler();

// Get values from text fields for class ID, class name, and ability type
String classID = txtClassID.getText();
String className = txtClassName.getText();
String abilityType = txtAbilityType.getText();

try {
    // Convert class ID to an integer
    int intClassID = Integer.parseInt(classID);

    // Call the updateClass method
    int result = ClassHand.updateClass(intClassID, intClassID, className, abilityType);

    // Check if the class was updated successfully
    if (result > 0) {
        // If successful, refresh the class table and show a success message
        refreshClassTable();
        JOptionPane.showMessageDialog(this, "Updated");
    } else {
        // If update failed, show a failure message
        JOptionPane.showMessageDialog(this, "Update Failed!");
    }
} catch (NumberFormatException e) {
    // Handle the exception for invalid integer input
    e.printStackTrace();
}



    }//GEN-LAST:event_cUpdateBttnActionPerformed

    private void cAddBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cAddBttnActionPerformed
// Create instances of the necessary classes for handling classes
ClassHandler ClassHand = new ClassHandler();

// Get values from text fields for class ID, class type, and class name
String ClassID = txtClassID.getText();
String ClassType = txtAbilityType.getText();
String ClassName = txtClassName.getText();

try {
    // Convert class ID to an integer
    int classID = Integer.parseInt(ClassID);

    // Call the addClass method to add a new class
    int result = ClassHand.addClass(classID, ClassName, ClassType);

    // Check if the class was added successfully
    if (result > 0) {
        // If successful, refresh the class table and show a success message
        refreshClassTable();
        JOptionPane.showMessageDialog(this, "Updated");
    } else {
        // If addition failed, show a failure message
        JOptionPane.showMessageDialog(this, "Addition Failed");
    }
} catch (NumberFormatException e) {
    // Handle the exception for invalid integer input
    e.printStackTrace();
}



    }//GEN-LAST:event_cAddBttnActionPerformed

    private void cDeleteBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDeleteBttnActionPerformed
        ClassHandler classHand = new ClassHandler();
        String ClassID = txtClassID.getText();
        int classID = Integer.parseInt(ClassID);
        
        
        int result = classHand.deleteClass(classID);
                
        if (result>0) {
            JOptionPane.showMessageDialog(this, "Armor deleted successfully.");
            refreshClassTable();}
        else{
            JOptionPane.showMessageDialog(this, "Armor deletion failed.");     
                    }
    }//GEN-LAST:event_cDeleteBttnActionPerformed

    private void cMenuBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMenuBttnActionPerformed
        this.setVisible(false);
        new EldenRingProj().setVisible(true);
    }//GEN-LAST:event_cMenuBttnActionPerformed
    public void refreshClassTable(){
        populateData("");
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cAddBttn;
    private javax.swing.JButton cDeleteBttn;
    private javax.swing.JButton cMenuBttn;
    private javax.swing.JButton cUpdateBttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClass;
    private javax.swing.JTextField txtAbilityType;
    private javax.swing.JTextField txtClassID;
    private javax.swing.JTextField txtClassName;
    // End of variables declaration//GEN-END:variables
}
