/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eldenringproj;

import bo.Mob;
import dao.MobHandler;
import dao.EnemyHandler;
import java.util.Iterator;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import utils.SQLUtil;


/**
 *
 * @author kilch
 */
public class EditMob extends javax.swing.JFrame {

    
    
    List<Mob> MobL;
    
    private void populateData(String keyword) {
        String[] colNames = new String[]{"Enemy ID"};
        DefaultTableModel tm = new DefaultTableModel(colNames, 0) {
            @Override
            public boolean isCellEditable(int i, int i1) {
                return false;
            }
        };
        MobL = new MobHandler().getMob(keyword);
        MobL.forEach((s) -> {
            tm.addRow(s.getRow());
        });
        tblMob.setModel(tm);
    }
    /**
     * Creates new form EditMob
     */
    public EditMob() {
        initComponents();
        populateData("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txteID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMob = new javax.swing.JTable();
        mDeleteBttn = new javax.swing.JButton();
        mMenuBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Gabriola", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(213, 174, 88));
        jLabel1.setText("Edit Mob");

        jLabel2.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(213, 174, 88));
        jLabel2.setText("Mob ID: ");

        txteID.setBackground(new java.awt.Color(213, 174, 88));
        txteID.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        tblMob.setBackground(new java.awt.Color(0, 0, 0));
        tblMob.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        tblMob.setForeground(new java.awt.Color(213, 174, 88));
        tblMob.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMob.setRowHeight(30);
        tblMob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMobMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMob);

        mDeleteBttn.setBackground(new java.awt.Color(213, 174, 88));
        mDeleteBttn.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        mDeleteBttn.setText("Delete Mob");
        mDeleteBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDeleteBttnActionPerformed(evt);
            }
        });

        mMenuBttn.setBackground(new java.awt.Color(213, 174, 88));
        mMenuBttn.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        mMenuBttn.setText("Menu");
        mMenuBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMenuBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txteID, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mMenuBttn)
                    .addComponent(mDeleteBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mDeleteBttn)
                        .addGap(156, 156, 156)
                        .addComponent(mMenuBttn)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblMobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMobMouseClicked
        int selectedRow = tblMob.getSelectedRow();
        if (selectedRow != -1) {
                    // Get values from the selected row
                    Object eIDValue = tblMob.getValueAt(selectedRow, 0);

                    // Set text fields with the retrieved values
                    txteID.setText(String.valueOf(eIDValue));

                    
                }
    }//GEN-LAST:event_tblMobMouseClicked

    private void mDeleteBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDeleteBttnActionPerformed
        EnemyHandler EnemyHand = new EnemyHandler();
        String MobID = txteID.getText();
        
        int enemyID = Integer.parseInt(MobID);
        
        int result = EnemyHand.deleteEnemy(enemyID);
                
        if (result>0) {
            JOptionPane.showMessageDialog(this, "Mob deleted successfully.");
            refreshMobTable();}
        else{
            JOptionPane.showMessageDialog(this, "Mob deletion failed.");     
                    }
    }//GEN-LAST:event_mDeleteBttnActionPerformed

    private void mMenuBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMenuBttnActionPerformed
        this.setVisible(false);
        new EldenRingProj().setVisible(true);
    }//GEN-LAST:event_mMenuBttnActionPerformed
    public void refreshMobTable(){
        populateData("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mDeleteBttn;
    private javax.swing.JButton mMenuBttn;
    private javax.swing.JTable tblMob;
    private javax.swing.JTextField txteID;
    // End of variables declaration//GEN-END:variables
}
