/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eldenringproj;
import bo.Weapon;
import dao.WeaponHandler;
import dao.ArmorHandler;
import dao.InventoryHandler;
import java.util.Iterator;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import utils.SQLUtil;
/**
 *
 * @author kilch
 */
public class WeaponOrArmor extends javax.swing.JFrame {

    /**
     * Creates new form WeaponOrArmor
     */
    public WeaponOrArmor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtWeaponiID = new javax.swing.JTextField();
        txtWeaponName = new javax.swing.JTextField();
        txtWeaponDMG = new javax.swing.JTextField();
        txtWeaponType = new javax.swing.JTextField();
        txtArmoriID = new javax.swing.JTextField();
        txtArmorName = new javax.swing.JTextField();
        txtDefenceStat = new javax.swing.JTextField();
        WeaponChoice = new javax.swing.JButton();
        ArmorChoice = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(213, 174, 88));
        jLabel1.setText("Weapon");

        jLabel3.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(213, 174, 88));
        jLabel3.setText("Armor");

        jLabel4.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(213, 174, 88));
        jLabel4.setText("Inventory ID:");

        jLabel5.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(213, 174, 88));
        jLabel5.setText("Weapon Name:");

        jLabel6.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(213, 174, 88));
        jLabel6.setText("Weapon Damage:");

        jLabel7.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(213, 174, 88));
        jLabel7.setText("Weapon Type: ");

        jLabel8.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(213, 174, 88));
        jLabel8.setText("Inventory ID:");

        jLabel9.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(213, 174, 88));
        jLabel9.setText("Armor Name: ");

        jLabel10.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(213, 174, 88));
        jLabel10.setText("Defense Stat:");

        txtWeaponiID.setBackground(new java.awt.Color(213, 174, 88));
        txtWeaponiID.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        txtWeaponName.setBackground(new java.awt.Color(213, 174, 88));
        txtWeaponName.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        txtWeaponDMG.setBackground(new java.awt.Color(213, 174, 88));
        txtWeaponDMG.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        txtWeaponType.setBackground(new java.awt.Color(213, 174, 88));
        txtWeaponType.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        txtArmoriID.setBackground(new java.awt.Color(213, 174, 88));
        txtArmoriID.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        txtArmorName.setBackground(new java.awt.Color(213, 174, 88));
        txtArmorName.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        txtDefenceStat.setBackground(new java.awt.Color(213, 174, 88));
        txtDefenceStat.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        WeaponChoice.setBackground(new java.awt.Color(213, 174, 88));
        WeaponChoice.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        WeaponChoice.setText("Add New Weapon");
        WeaponChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeaponChoiceActionPerformed(evt);
            }
        });

        ArmorChoice.setBackground(new java.awt.Color(213, 174, 88));
        ArmorChoice.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        ArmorChoice.setText("Add New Armor");
        ArmorChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArmorChoiceActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(213, 174, 88));
        jButton1.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        jButton1.setText("Back to Inventory");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtWeaponName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtWeaponDMG))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtWeaponType))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtWeaponiID, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(WeaponChoice))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtArmorName, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(txtArmoriID, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDefenceStat)))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ArmorChoice)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel8))
                    .addComponent(txtWeaponiID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArmoriID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(txtWeaponName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArmorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtWeaponDMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDefenceStat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtWeaponType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WeaponChoice)
                    .addComponent(ArmorChoice))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(630, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(132, 132, 132))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WeaponChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeaponChoiceActionPerformed
// Create instances of the WeaponHandler, InventoryHandler, and EditInventory classes
WeaponHandler WeaponHand = new WeaponHandler();
InventoryHandler InvHand = new InventoryHandler();
EditInventory EI = new EditInventory();

// Get values from text fields for weapon ID, damage, type, and name
String WeaponID = txtWeaponiID.getText();
String WeaponDMG = txtWeaponDMG.getText();
String WeaponType = txtWeaponType.getText();
String WeaponName = txtWeaponName.getText();

try {
    // Convert weapon ID and damage to integers
    int weaponID = Integer.parseInt(WeaponID);
    int weaponDMG = Integer.parseInt(WeaponDMG);

    // Call methods to add new weapon and inventory instances
    int result2 = InvHand.addInventory(weaponID, WeaponName);
    int result = WeaponHand.addWeapon(weaponID, weaponDMG, WeaponType);

    // Check if both weapon and inventory were successfully added
    if (result > 0 && result2 > 0) {
        // If successful, hide current window, open edit inventory window, refresh table, and show success message
        this.setVisible(false);
        new EditInventory().setVisible(true);
        EI.refreshInventoryTable();
        JOptionPane.showMessageDialog(this, "Updated");
    } else {
        // If adding failed, show update fail message
    }
} catch (NumberFormatException e) {
    // Handle the exception for invalid integer input
    e.printStackTrace();
}

    }//GEN-LAST:event_WeaponChoiceActionPerformed

    private void ArmorChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArmorChoiceActionPerformed
// Create instances of the ArmorHandler, InventoryHandler, and EditInventory classes
ArmorHandler ArmorHand = new ArmorHandler();
InventoryHandler InvHand = new InventoryHandler();
EditInventory EI = new EditInventory();

// Get values from text fields for armor ID, name, and defense statistic
String ArmorID = txtArmoriID.getText();
String ArmorName = txtArmorName.getText();
String ArmorDefStat = txtDefenceStat.getText();

try {
    // Convert armor ID and defense statistic to integers
    int armorID = Integer.parseInt(ArmorID);
    int armorDefStat = Integer.parseInt(ArmorDefStat);

    // Call methods to add new armor and inventory instances
    int result2 = InvHand.addInventory(armorID, ArmorName);
    int result = ArmorHand.addArmor(armorID, armorDefStat);

    // Check if both armor and inventory were successfully added
    if (result > 0 && result2 > 0) {
        // If successful, hide current window, open edit inventory window, refresh table, and show success message
        this.setVisible(false);
        new EditInventory().setVisible(true);
        EI.refreshInventoryTable();
        JOptionPane.showMessageDialog(this, "Updated");
    } else {
        // If adding failed, do nothing
    }
} catch (NumberFormatException e) {
    // Handle the exception for invalid integer input
    e.printStackTrace();
}

    }//GEN-LAST:event_ArmorChoiceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new EditInventory().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ArmorChoice;
    private javax.swing.JButton WeaponChoice;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtArmorName;
    private javax.swing.JTextField txtArmoriID;
    private javax.swing.JTextField txtDefenceStat;
    private javax.swing.JTextField txtWeaponDMG;
    private javax.swing.JTextField txtWeaponName;
    private javax.swing.JTextField txtWeaponType;
    private javax.swing.JTextField txtWeaponiID;
    // End of variables declaration//GEN-END:variables
}
